theme: jekyll-theme-slate
title: Mémos
description: Mes mots techniques
author: TheSubmarine
description: > # this means to ignore newlines until "baseurl:"
  Les mémos techniques
# social links
twitter_username: thesubmarine # DO NOT include the @ character, or else the build will fail!
github_username:  brahimmachkouri # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
