theme: jekyll-theme-slate
title: "A GitHub Pages site to showcase repository metadata"
project.title: "A GitHub Pages site to showcase repository metadata"
project_title: "metadata-example",
project_tagline: "A GitHub Pages site to showcase repository metadata2"
